az pipelines run --name Hub.Extensions --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Storage.Dto.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Storage.Entities.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Settings.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Logging --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Storage.Repository.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Settings --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Storage.Repository --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Commands.Logging.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Commands.Logging --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Commands.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.Commands.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.InternalQueueHostedService.Queue.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.InternalQueueHostedService.Queue --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.InternalQueueHostedService --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Commands.Configuration.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Schedule.Commands.Core --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Commands.Configuration --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Storage --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Web.Api --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Web.Http --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.Web.BlazorServer --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Schedule.Commands --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Schedule.HostedService --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.Commands --organization https://rhe89.visualstudio.com --project Hub
az pipelines run --name Hub.HostedServices.Queue.ServiceBusQueueHostedService --organization https://rhe89.visualstudio.com --project Hub
