sh /Users/Privat/repos/hub/hub-shared/Hub.Extensions/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Settings.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Logging/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Settings/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Storage/Hub.Storage.Entities.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Storage/Hub.Storage.Dto.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Storage/Hub.Storage.Repository/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Storage/Hub.Storage.Repository.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Web/Hub.Web.Api/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Web/Hub.Web.Http/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.Web/Hub.Web.BlazorServer/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.Commands.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Storage/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Commands.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Schedule.HostedService/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.Commands/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.InternalQueueHostedService.Queue/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Commands.Logging.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Commands.Logging/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Schedule.Commands/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Commands.Configuration.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Commands.Configuration/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.ServiceBusQueueHostedService/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.InternalQueueHostedService/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Queue.InternalQueueHostedService.Queue.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Core/az-pipeline-create.sh
sh /Users/Privat/repos/hub/hub-shared/Hub.HostedServices/Hub.HostedServices.Schedule.Commands.Core/az-pipeline-create.sh
