trigger: none

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    projects: '**/$(projectName).NuGet.csproj'
    feedsToUse: 'select'
    vstsFeed: 'a9ebd0d9-61ca-407b-bd4f-cf5e1f59a5c6'
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/$(projectName).NuGet.csproj'
    arguments: '--no-restore'
- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(projectName).NuGet.csproj'
    nobuild: true
    versioningScheme: 'off'
- task: NuGetAuthenticate@0
  displayName: 'authenticate'
- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a9ebd0d9-61ca-407b-bd4f-cf5e1f59a5c6'
    allowPackageConflicts: true