steps:
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources remove -Name github'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources add -source https://nuget.pkg.github.com/rhe89/index.json -StorePasswordInClearText -Name github -UserName rhe89 -Password $(nugetAccessToken)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack $(buildConfiguration)'
  inputs:
    command: pack
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget Github'